### ISSUE TITLE
How to fix child theme to be active for it to work?

### ISSUE THREAD

**Issue by rmostafizur965-tredningstyle** [AvanamOrg/avanam#4]
I recently saw the notification on my website. How can I fix the issue? Please take a look at my attached images.
 
![Screenshot_8](https://github.com/user-attachments/assets/3f20e4c9-9c29-4b63-8681-8d69fd92de96)
![Screenshot_11](https://github.com/user-attachments/assets/e25bf78a-81b1-460f-a667-77a237d961e0)

**Comment by alinashevchenkome** [comment]
1. For "avanam" theme directory notice you have to install avanam theme.
2. Its related to thirdparty plugins. It;s not avanam related issues.
